POST http://localhost:4002/insertProduct 
content-type: application/json

{
    "name": "Lápis",
    "price": 1.8
}

###
GET http://localhost:4002/findAllProducts

###
GET http://localhost:4002/findProduct/75164e89-bbed-432e-80a2-980fde914926

###
PUT http://localhost:4002/updateProduct/6d39aef1-c687-43d1-a52a-8ed52a3dd4b0
content-type: application/json

{
    "name": "Caneta Rosa",
    "price": 4.55
}

###
DELETE http://localhost:4002/deleteProduct/18ce5d7a-bf7f-454d-b0fc-f307f84824ed